---
- name: Verify Active/Standby Sup 
  hosts: "ios_test"
  serial: 1
  gather_facts: false
  connection: local

  roles:
    - ansible-network.network-engine


  vars:
    ansible_command_timeout: 3660


  tasks:


    - name:  sh redundancy
      ios_command:
        commands:
          - sh redundancy
      register: redundancy


    - name: Command parser
      command_parser:
         file: "./parser/act_sup.yml"
         content: "{{ redundancy.stdout[0] }}"


    - name: DISPLAY ACTIVE SUP
      debug:
        msg: " Active Sup number is {{ sup_active_facts['active'][0] | int }}"

    - name: DISPLAY STANDBY SUP
      debug:
        msg: " Standby Sup number is {{ sup_standby_facts['standby'][0] | int }}"

    - name: DISPLAY ISSU COMMAND
      debug:
        msg: "issu changeversion {{ sup_active_facts['active'][0] }} bootflash:cat4500es8-universalk9.SPA.03.08.06.E.152-4.E6.bin {{ sup_standby_facts['standby'][0] }} slavebootflash:cat4500es8-universalk9.SPA.03.08.06.E.152-4.E6.bin"

    - pause:
        minutes: 1

    - name: Collect Facts
      ios_facts:
         gather_subset: hardware
      register: output

    - name: show output
      debug:
        msg:  "{{ ansible_net_hostname }}, {{ ansible_net_version }}, non-compliant"
      when: ansible_net_version != '03.08.06.E'

    - name: show output
      debug:
        msg:  "{{ ansible_net_hostname }}, {{ ansible_net_version }}, compliant"
      when: ansible_net_version == '03.08.06.E'    

    - name: send mail compliant
      mail:
        host: mail.domain.com 
        port: 25
        charset: utf-8
        from: user@domain.com
        to: user@domain.com
        subject: "Ansible Report for {{ ansible_net_hostname }}"
        body: 'Switch {{ ansible_net_hostname }} has been SUCCESSFULLY upgraded {{ ansible_net_version }}' 
      delegate_to: localhost
      when: ansible_net_version == '03.08.06.E'


    - name: send mail non-compliant
      mail:
        host: mail.domain.com
        port: 25
        charset: utf-8
        from: user@domain.com
        to: user@domain.com
        subject: "Ansible Report for {{ ansible_net_hostname }}"
        body: 'Switch {{ ansible_net_hostname }} has NOT been upgraded  current version is {{ ansible_net_version }}'
      delegate_to: localhost
      when: ansible_net_version != '03.08.06.E'
